renelems_backoffice:
    resource: "@RenelemsBackofficeBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
renelems_website:
    resource: "@RenelemsWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /