security:
    firewalls:
        admin:
            pattern:    ^/admin
            anonymous: ~
            form_login:
                login_path:  admin_login
                check_path:  admin_login_check
            logout:
                path:   admin_logout
                target: admin_login

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        admin:
            entity:
                class: Renelems\DBBundle\Entity\Admin
                property: email

    encoders:
        Renelems\DBBundle\Entity\Admin:
            id: renelems.managers.password.admin

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
